development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 477246480092-rmf2ruecdfd7nigm1pbn1mcqb1ivjuk3.apps.googleusercontent.com
  google_client_secret: A7aLLkD1mKak_7-rz7_urTkX
